### ISSUE TITLE
No mapping to Wikidata in PV?

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/create-bridgedb-metabolites#11]
When I was working on a Lipid Maps PW, I saw the following mapping in the backpage:

![image](https://user-images.githubusercontent.com/26277832/51841952-1927d300-2310-11e9-86f0-99fe7633f8d4.png)

One of the LipidMaps IDs (ending with 42) does not exist in Lipid Maps; I found out it originated from Wikidata. It was added at: 
```
(cur | prev)  15:04, 31 May 2018‎ Reinheitsgebot (talk | contribs)‎ . . (33,079 bytes) +354‎ . . (‎Created claim: LIPID MAPS ID (P2063): LMFA03060042, #quickstatements; invoked by Mix'n'match:Auxiliary sync) (undo) (restore)
```

I removed this not existing ID from Wikidata, however there is no mentioning of a Wikidata ID in the backpage.... why not?
(The double cas number is not on Wikidata, but I have no idea where it is originating from...)
@egonw

**Comment by egonw** [comment]
I cannot see how this did not come from Wikidata... we should test again after the next metabolite mapping database release.

**Comment by DeniseSl22** [comment]
I have seen some more of these "glitches" in Pathvisio.... sometimes when you load the data in the backpage again (by first clicking on another DataNode, then going back to the original one), the mappings do appear... bit weird behavior, but I don't think it is related to the mapping files itself. If I see this again, I'll contact Tina.
