### ISSUE TITLE
Wrong InchiKeys

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/create-bridgedb-metabolites#20]
One of my interns (@IreneHemel) is working on identifier mappings between metabolites.
She checked for the HMDB IDs that were given in IEMBase (as biomarkers for diseases), if these have any mappings to ChEBI (and if yes, which ones they are). She needs the ChEBI IDs to map correctly, since these are represented in the PWs she is working on.
While doing this checking of mappings, she found some compounds to have two InChiKeys, for example for Thymine (HMDB0000262):

![image](https://user-images.githubusercontent.com/26277832/57615656-85a3a680-757c-11e9-8632-8a1c35e60692.png)

RWQNBRDOKXIBIV-UHFFFAOYSA-N	InChIKey  (Correct)
![image](https://user-images.githubusercontent.com/26277832/57615736-b1bf2780-757c-11e9-846a-e90e19197305.png)

YQHWOOLBIREPRR-VZUYHUTRSA-N	InChIKey  (Wrong)
![image](https://user-images.githubusercontent.com/26277832/57615754-bbe12600-757c-11e9-9f41-a84e8caf3589.png)

However, one of the inchiKeys is completely wrong (I looked for them through ChemSpider, see above).

I've tried to track where this mapping originates from (HMDB, ChEBI or Wikidata), however the wrong InchiKey is not present in any of them.... so I'm wondering why it is even queryable in the webservice of BridgeDb. According to the properties query, there are several metabolite-mapping files loaded (even originating from 2013!):
![image](https://user-images.githubusercontent.com/26277832/57615871-14182800-757d-11e9-9431-f5641161ad2e.png)

So, I think we need to make sure that:
1. Only 1 ID mapping set is loaded per DataNode/Interaction type. @nunogit 
2. Build a check for conflicting InChiKeys (the part before the first '-' should at least be similar, otherwise the structure is different). @egonw 

@IreneHemel has several other examples, if needed. Some more are below:
HMDB0000300 (2 inchikeys, PRFVPHBJWNBZBM-GGCSAXROSA-N not retrievable through scholia(=wikidata), chemspider and chebi).
HMDB0000273 (2 inchikeys, KHUMAHPJNTVTEQ-DXQCBLCSSA-N not retrievable through scholia(=wikidata), chemspider and chebi).

**Comment by egonw** [comment]
This is a good use case to have more provenance of the history of that mapping.

@DeniseSl22, can you ask Irene to verify with locally with only the latest ID mapping file? Having more than one is bound to give issues, and maybe the only reason. At this moment we do not know if this is a problem in the code, in the data, or in the webservice.

**Comment by DeniseSl22** [comment]
Yes I'll check together with her; we could use the R-script tutorial you added to the Tess portal of Elixir.

**Comment by DeniseSl22** [comment]
@IreneHemel : https://tess.elixir-europe.org/materials/bridgedbr-tutorial#home

**Comment by IreneHemel** [comment]
I checked it for all HMDB IDs that reported a second Inchikey in the webservice, using the metabolites_20190509 file and only one Inchikey is reported back, the one that is also stated on the HMBD and ChEBI websites

**Comment by DeniseSl22** [comment]
Okay thank you for checking @IreneHemel ! Then it's probably finding old inchikeys due to old mapping files that are loaded. @nunogit , what's the status of removing old versions of metabolomics mapping files :)?

**Comment by DeniseSl22** [comment]
Okay, @nunogit removed the old mapping files, and here is the result:
![image](https://user-images.githubusercontent.com/26277832/58426346-79e7d200-809c-11e9-9d56-a21542f1278c.png)

I check the three examples above, and they all now give 1 InchiKey. Also the "metadata" query indicated that only one metabolite.bridge file is loaded :D.
