### ISSUE TITLE
(Jenkins) build failure for Bridgedb 2.3.8 (secondary IDs).

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/create-bridgedb-metabolites#26]
When I updated the code with the latest BridgeDb libraries https://github.com/bridgedb/create-bridgedb-metabolites/commit/0162ff1197ac4eb73207409ba5a8b6e2ae8bfd07, I got the following build failure in Jenkins:
```
+ CLASSPATH=derby.jar:org.bridgedb.bio.jar:org.bridgedb.jar:org.bridgedb.rdb.construct.jar:org.bridgedb.rdb.jar:. groovy createDerby.groovy
Caught: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.bridgedb.Xref(java.lang.String, org.bridgedb.DataSource, java.lang.Boolean)
groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.bridgedb.Xref(java.lang.String, org.bridgedb.DataSource, java.lang.Boolean)
	at createDerby$_run_closure2.doCall(createDerby.groovy:167)
	at createDerby.run(createDerby.groovy:140)
Build step 'Execute shell' marked build as failure
Archiving artifacts
Recording test results
Finished: FAILURE
```

Apparently this happened before, see https://github.com/bridgedb/create-bridgedb-metabolites/commit/70b24a37a1f5df1228527a5035d6c51a343409f6 . What should be done, to get the Xref class compatible with the secondary IDs additions?

**Comment by egonw** [comment]
Turns out we're already using master for this tool. I forgot about that. But it was because of secondary ID support. But the tool is currently still set to create BridgeDb 2.3 (schema 3) version Derby databaes.
