### ISSUE TITLE
Compatibility with new HMDb IDs

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/create-bridgedb-metabolites#3]
For the last Metabolite Bridge that was created (20180111), there is no mapping to the new HMDb IDs (HMDB00XXXXX). If I remove the extra zero's for all identifiers, all data is recognised in Pathvisio.
We should find a way to map HMDBXXXXX to HMDB00XXXXX!

**Comment by egonw** [comment]
Believed to be fixed.
