### ISSUE TITLE
Check retired LIPID MAPS IDs

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/create-bridgedb-metabolites#32]
![image](https://user-images.githubusercontent.com/26277832/104011279-201f1780-51ae-11eb-8ce7-0384b3407443.png)

**Comment by DeniseSl22** [comment]
More info:

"Removal of classes based on lipid source
In keeping with the theme of having a classification scheme dictated by molecular structure and function, the sterol lipid subclasses Phytosterols, Marine sterols and Fungal sterols were retired because these refer to the lipid source (marine) or biological kingdom (plants,fungi). It is possible to identify a particular sterol in more than one of these 3 sources. These subclasses have been replaced by a new set of subclasses based on the carbon skeleton of the sterol core structure (Ergosterols, Gorgosterols, Furostanols,etc.). The details are outlined under the Sterol lipids section below." https://www.lipidmaps.org/data/classification/classification_updates.html

**Comment by DeniseSl22** [comment]
The link above also mentions several other IDs which have been removed (do ctrl+f for removed)..... manual work for now, but I think it's worth looking into

**Comment by egonw** [comment]
That link is about classes. That's a lot harder and we don't have a lot of them in WikiPathways anyway.

**Comment by egonw** [comment]
Test added.
