### ISSUE TITLE
Update ChEBI secondary IDs #nwobridgedb

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/create-bridgedb-metabolites#39]
Now read in from (outdated) file: https://github.com/bridgedb/create-bridgedb-metabolites/blob/master/deprecated_ChEBI.csv
Code: https://github.com/bridgedb/create-bridgedb-metabolites/blob/master/createDerby.groovy#L132-L141

Needs to be read in from tsv file (if possible): https://github.com/bridgedb/create-bridgedb-metabolites/blob/master/createDerby.groovy#L263-L301

**Comment by tabbassidaloii** [comment]
what is the source of [deprecated_ChEBI.csv](https://github.com/bridgedb/create-bridgedb-metabolites/blob/master/deprecated_ChEBI.csv) table?

**Comment by egonw** [comment]
I am not sure. I need to dig that up.

**Comment by egonw** [comment]
> I am not sure. I need to dig that up.

I cannot find where I got this data from / how I created the file.

**Comment by DeniseSl22** [comment]
No worries, @tabbassidaloii managed to create a new version https://github.com/tabbassidaloii/create-bridgedb-secondary2primary
