### ISSUE TITLE
Check KEGG query #nwobridgedb

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/create-bridgedb-metabolites#41]
The Kegg query is now also retrieving reaction IDs https://www.wikidata.org/wiki/Q14863662 and diseases https://www.wikidata.org/wiki/Q112412.

@egonw

**Comment by egonw** [comment]
Fixed with https://github.com/bridgedb/create-bridgedb-metabolites/commit/dafd2dd906d28c706da058b02b8f74c63b319234
